### ISSUE TITLE
Update year

### ISSUE THREAD

**Issue by MrWoWander** [RTUITLab/Landing-Front#29]
Обновить год на сайте. У нас уже 2021 :smile:

![year](https://imageup.ru/img177/3715462/snimok-ekrana-2021-03-11-v-104608.jpg)

**Comment by CAPCHIK** [comment]
@Suput  - надо прокидывать эту дату при сборке, например js скриптом. Если я помню  верно на фронте начинает использоваться Jake, он отлично справится с этой задачей

**Comment by CAPCHIK** [comment]
Ну и важно сделать именно так, чтобы этот параметр **нельзя** было менять после сборки. Обычно стараемся делать наоборот, но год сборки это как раз хороший пример параметра, который нужно именно зашить
